# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: patch.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'patch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bpatch.proto\x12\x05\x61g_ui\x1a\x1cgoogle/protobuf/struct.proto\"\x9f\x01\n\x12JsonPatchOperation\x12)\n\x02op\x18\x01 \x01(\x0e\x32\x1d.ag_ui.JsonPatchOperationType\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x11\n\x04\x66rom\x18\x03 \x01(\tH\x00\x88\x01\x01\x12*\n\x05value\x18\x04 \x01(\x0b\x32\x16.google.protobuf.ValueH\x01\x88\x01\x01\x42\x07\n\x05_fromB\x08\n\x06_value*X\n\x16JsonPatchOperationType\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\n\n\x06REMOVE\x10\x01\x12\x0b\n\x07REPLACE\x10\x02\x12\x08\n\x04MOVE\x10\x03\x12\x08\n\x04\x43OPY\x10\x04\x12\x08\n\x04TEST\x10\x05\x42\x17\xaa\x02\x14\x41GUI.ProtocolBuffersb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'patch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\024AGUI.ProtocolBuffers'
  _globals['_JSONPATCHOPERATIONTYPE']._serialized_start=214
  _globals['_JSONPATCHOPERATIONTYPE']._serialized_end=302
  _globals['_JSONPATCHOPERATION']._serialized_start=53
  _globals['_JSONPATCHOPERATION']._serialized_end=212
# @@protoc_insertion_point(module_scope)
