import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: Align traces with current main after merged checkpoint-pinned boundary snapshots; keep environment version metadata normalized
// Before accepting changes, verify whether the implementation regressed.
const shared1 = {
  event: "on_chat_model_stream",
  data: {
    chunk: {
      content: "I can see the image ",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
      },
      type: "AIMessageChunk",
      name: null,
      id: "id-4",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
      tool_call_chunks: [],
      chunk_position: null,
    },
  },
  run_id: "id-5",
  name: "ChatOpenAI",
  tags: ["seq:step:1"],
  metadata: {
    thread_id: "id-1",
    ls_integration: "langchain_chat_model",
    langgraph_step: 1,
    langgraph_node: "chat_node",
    langgraph_triggers: ["branch:to:chat_node"],
    langgraph_path: ["__pregel_pull", "chat_node"],
    langgraph_checkpoint_ns: "chat_node:id-6",
    checkpoint_ns: "chat_node:id-6",
    ls_provider: "openai",
    ls_model_name: "gpt-5.4",
    ls_model_type: "chat",
    ls_temperature: null,
  },
  parent_ids: ["id-7", "id-8"],
} as const;
const shared2 = {
  content: [
    {
      type: "text",
      text: "Tell me what do you see in this image",
    },
    {
      type: "image_url",
      image_url: {
        url: "data:image/png;base64,dmVyc2lvbiBodHRwczovL2dpdC1sZnMuZ2l0aHViLmNvbS9zcGVjL3YxCm9pZCBzaGEyNTY6OTRkMjRjZTE2NDcwZTg1YjlmY2I0MWRlMDZiMzAwOWNjODM1YWQxMTM4ZjgwMTI4NDVlNmFiOTlkMDA3ZGQ2YwpzaXplIDcwCg==",
      },
    },
  ],
  additional_kwargs: {},
  response_metadata: {},
  type: "human",
  name: null,
  id: "id-3",
} as const;
const shared3 = {
  content:
    "I can see the image you've shared. It appears to contain visual content that I can analyze. Let me describe what I observe in detail for you.",
  additional_kwargs: {},
  response_metadata: {
    finish_reason: "stop",
    model_name: "gpt-5.4",
    model_provider: "openai",
  },
  type: "ai",
  name: null,
  id: "id-4",
  tool_calls: [],
  invalid_tool_calls: [],
  usage_metadata: null,
} as const;
const shared4 = [
  {
    name: "change_background",
    description:
      "Change the background color of the chat. Can be anything that the CSS background attribute accepts. Regular colors, linear or radial gradients etc.",
    parameters: {
      type: "object",
      properties: {
        background: {
          type: "string",
          description: "The background. Prefer gradients. Only use when asked.",
        },
      },
      required: ["background"],
    },
  },
] as const;
const shared5 = {
  type: "data",
  value:
    "dmVyc2lvbiBodHRwczovL2dpdC1sZnMuZ2l0aHViLmNvbS9zcGVjL3YxCm9pZCBzaGEyNTY6OTRkMjRjZTE2NDcwZTg1YjlmY2I0MWRlMDZiMzAwOWNjODM1YWQxMTM4ZjgwMTI4NDVlNmFiOTlkMDA3ZGQ2YwpzaXplIDcwCg==",
  mimeType: "image/png",
} as const;

export const agenticChatMultimodalPageEventTrace = defineEventTrace(
  import.meta.url,
  {
    uploadAnImageAndReceiveADescription: [
      {
        type: "RUN_STARTED",
        threadId: "id-1",
        runId: "id-2",
        input: {
          threadId: "id-1",
          runId: "id-2",
          state: {},
          messages: [
            {
              id: "id-3",
              role: "user",
              content: [
                {
                  type: "text",
                  text: "Tell me what do you see in this image",
                },
                {
                  type: "image",
                  source: shared5,
                  metadata: {
                    filename: "test-image.png",
                  },
                },
              ],
            },
          ],
          tools: shared4,
          context: [],
          forwardedProps: {},
        },
      },
      {
        type: "STEP_STARTED",
        stepName: "chat_node",
      },
      {
        type: "TEXT_MESSAGE_START",
        rawEvent: shared1,
        messageId: "id-4",
        role: "assistant",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        rawEvent: shared1,
        messageId: "id-4",
        delta: "I can see the image ",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        rawEvent: {
          event: "on_chat_model_stream",
          data: {
            chunk: {
              content: "you've shared. It ap",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
              },
              type: "AIMessageChunk",
              name: null,
              id: "id-4",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
              tool_call_chunks: [],
              chunk_position: null,
            },
          },
          run_id: "id-5",
          name: "ChatOpenAI",
          tags: ["seq:step:1"],
          metadata: {
            thread_id: "id-1",
            ls_integration: "langchain_chat_model",
            langgraph_step: 1,
            langgraph_node: "chat_node",
            langgraph_triggers: ["branch:to:chat_node"],
            langgraph_path: ["__pregel_pull", "chat_node"],
            langgraph_checkpoint_ns: "chat_node:id-6",
            checkpoint_ns: "chat_node:id-6",
            ls_provider: "openai",
            ls_model_name: "gpt-5.4",
            ls_model_type: "chat",
            ls_temperature: null,
          },
          parent_ids: ["id-7", "id-8"],
        },
        messageId: "id-4",
        delta: "you've shared. It ap",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        rawEvent: {
          event: "on_chat_model_stream",
          data: {
            chunk: {
              content: "pears to contain vis",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
              },
              type: "AIMessageChunk",
              name: null,
              id: "id-4",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
              tool_call_chunks: [],
              chunk_position: null,
            },
          },
          run_id: "id-5",
          name: "ChatOpenAI",
          tags: ["seq:step:1"],
          metadata: {
            thread_id: "id-1",
            ls_integration: "langchain_chat_model",
            langgraph_step: 1,
            langgraph_node: "chat_node",
            langgraph_triggers: ["branch:to:chat_node"],
            langgraph_path: ["__pregel_pull", "chat_node"],
            langgraph_checkpoint_ns: "chat_node:id-6",
            checkpoint_ns: "chat_node:id-6",
            ls_provider: "openai",
            ls_model_name: "gpt-5.4",
            ls_model_type: "chat",
            ls_temperature: null,
          },
          parent_ids: ["id-7", "id-8"],
        },
        messageId: "id-4",
        delta: "pears to contain vis",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        rawEvent: {
          event: "on_chat_model_stream",
          data: {
            chunk: {
              content: "ual content that I c",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
              },
              type: "AIMessageChunk",
              name: null,
              id: "id-4",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
              tool_call_chunks: [],
              chunk_position: null,
            },
          },
          run_id: "id-5",
          name: "ChatOpenAI",
          tags: ["seq:step:1"],
          metadata: {
            thread_id: "id-1",
            ls_integration: "langchain_chat_model",
            langgraph_step: 1,
            langgraph_node: "chat_node",
            langgraph_triggers: ["branch:to:chat_node"],
            langgraph_path: ["__pregel_pull", "chat_node"],
            langgraph_checkpoint_ns: "chat_node:id-6",
            checkpoint_ns: "chat_node:id-6",
            ls_provider: "openai",
            ls_model_name: "gpt-5.4",
            ls_model_type: "chat",
            ls_temperature: null,
          },
          parent_ids: ["id-7", "id-8"],
        },
        messageId: "id-4",
        delta: "ual content that I c",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        rawEvent: {
          event: "on_chat_model_stream",
          data: {
            chunk: {
              content: "an analyze. Let me d",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
              },
              type: "AIMessageChunk",
              name: null,
              id: "id-4",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
              tool_call_chunks: [],
              chunk_position: null,
            },
          },
          run_id: "id-5",
          name: "ChatOpenAI",
          tags: ["seq:step:1"],
          metadata: {
            thread_id: "id-1",
            ls_integration: "langchain_chat_model",
            langgraph_step: 1,
            langgraph_node: "chat_node",
            langgraph_triggers: ["branch:to:chat_node"],
            langgraph_path: ["__pregel_pull", "chat_node"],
            langgraph_checkpoint_ns: "chat_node:id-6",
            checkpoint_ns: "chat_node:id-6",
            ls_provider: "openai",
            ls_model_name: "gpt-5.4",
            ls_model_type: "chat",
            ls_temperature: null,
          },
          parent_ids: ["id-7", "id-8"],
        },
        messageId: "id-4",
        delta: "an analyze. Let me d",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        rawEvent: {
          event: "on_chat_model_stream",
          data: {
            chunk: {
              content: "escribe what I obser",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
              },
              type: "AIMessageChunk",
              name: null,
              id: "id-4",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
              tool_call_chunks: [],
              chunk_position: null,
            },
          },
          run_id: "id-5",
          name: "ChatOpenAI",
          tags: ["seq:step:1"],
          metadata: {
            thread_id: "id-1",
            ls_integration: "langchain_chat_model",
            langgraph_step: 1,
            langgraph_node: "chat_node",
            langgraph_triggers: ["branch:to:chat_node"],
            langgraph_path: ["__pregel_pull", "chat_node"],
            langgraph_checkpoint_ns: "chat_node:id-6",
            checkpoint_ns: "chat_node:id-6",
            ls_provider: "openai",
            ls_model_name: "gpt-5.4",
            ls_model_type: "chat",
            ls_temperature: null,
          },
          parent_ids: ["id-7", "id-8"],
        },
        messageId: "id-4",
        delta: "escribe what I obser",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        rawEvent: {
          event: "on_chat_model_stream",
          data: {
            chunk: {
              content: "ve in detail for you",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
              },
              type: "AIMessageChunk",
              name: null,
              id: "id-4",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
              tool_call_chunks: [],
              chunk_position: null,
            },
          },
          run_id: "id-5",
          name: "ChatOpenAI",
          tags: ["seq:step:1"],
          metadata: {
            thread_id: "id-1",
            ls_integration: "langchain_chat_model",
            langgraph_step: 1,
            langgraph_node: "chat_node",
            langgraph_triggers: ["branch:to:chat_node"],
            langgraph_path: ["__pregel_pull", "chat_node"],
            langgraph_checkpoint_ns: "chat_node:id-6",
            checkpoint_ns: "chat_node:id-6",
            ls_provider: "openai",
            ls_model_name: "gpt-5.4",
            ls_model_type: "chat",
            ls_temperature: null,
          },
          parent_ids: ["id-7", "id-8"],
        },
        messageId: "id-4",
        delta: "ve in detail for you",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        rawEvent: {
          event: "on_chat_model_stream",
          data: {
            chunk: {
              content: ".",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
              },
              type: "AIMessageChunk",
              name: null,
              id: "id-4",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
              tool_call_chunks: [],
              chunk_position: null,
            },
          },
          run_id: "id-5",
          name: "ChatOpenAI",
          tags: ["seq:step:1"],
          metadata: {
            thread_id: "id-1",
            ls_integration: "langchain_chat_model",
            langgraph_step: 1,
            langgraph_node: "chat_node",
            langgraph_triggers: ["branch:to:chat_node"],
            langgraph_path: ["__pregel_pull", "chat_node"],
            langgraph_checkpoint_ns: "chat_node:id-6",
            checkpoint_ns: "chat_node:id-6",
            ls_provider: "openai",
            ls_model_name: "gpt-5.4",
            ls_model_type: "chat",
            ls_temperature: null,
          },
          parent_ids: ["id-7", "id-8"],
        },
        messageId: "id-4",
        delta: ".",
      },
      {
        type: "TEXT_MESSAGE_END",
        rawEvent: {
          event: "on_chat_model_end",
          data: {
            output: shared3,
            input: {
              messages: [
                [
                  {
                    content:
                      "You are a helpful assistant that can analyze images, documents, and other media. When a user shares an image, describe what you see in detail. When a user shares a document, summarize its contents.",
                    additional_kwargs: {},
                    response_metadata: {},
                    type: "system",
                    name: null,
                    id: null,
                  },
                  shared2,
                ],
              ],
            },
          },
          run_id: "id-5",
          name: "ChatOpenAI",
          tags: ["seq:step:1"],
          metadata: {
            thread_id: "id-1",
            ls_integration: "langchain_chat_model",
            langgraph_step: 1,
            langgraph_node: "chat_node",
            langgraph_triggers: ["branch:to:chat_node"],
            langgraph_path: ["__pregel_pull", "chat_node"],
            langgraph_checkpoint_ns: "chat_node:id-6",
            checkpoint_ns: "chat_node:id-6",
            ls_provider: "openai",
            ls_model_name: "gpt-5.4",
            ls_model_type: "chat",
            ls_temperature: null,
          },
          parent_ids: ["id-7", "id-8"],
        },
        messageId: "id-4",
      },
      {
        type: "STEP_FINISHED",
        stepName: "chat_node",
      },
      {
        type: "STATE_SNAPSHOT",
        snapshot: {
          messages: [shared2, shared3],
          tools: shared4,
        },
      },
      {
        type: "MESSAGES_SNAPSHOT",
        messages: [
          {
            id: "id-3",
            role: "user",
            content: [
              {
                type: "text",
                text: "Tell me what do you see in this image",
              },
              {
                type: "image",
                source: shared5,
              },
            ],
          },
          {
            id: "id-4",
            role: "assistant",
            content:
              "I can see the image you've shared. It appears to contain visual content that I can analyze. Let me describe what I observe in detail for you.",
          },
        ],
      },
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-2",
      },
    ],
  },
);
